runs:
  using: "composite"
  steps:
  - name: Install dependencies
    run: |
      curl -sSLO https://pdm-project.org/install-pdm.py
      curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
      python3 install-pdm.py
      pdm install
    shell: bash

  - name: Lint
    run: |
      pdm run black $PROJECT_SRC_REL $PROJECT_SETUP --check
      pdm run flake8 --ignore F401 $PROJECT_SRC_REL $PROJECT_SETUP
    shell: bash

  - name: PDM install
    run: pdm install
    shell: bash

  - name: conan install
    run: |
      source .venv/bin/activate
      conan --version
      conan profile detect
      conan install --build=missing .
    shell: bash

  - name: test
    run: |
      pdm run pytest -o log_level=DEBUG -o log_cli=True tests/
    shell: bash

