runs:
  using: "composite"
  steps:
  - name: Install dependencies
    run: |
      curl -sSLO https://pdm-project.org/install-pdm.py
      curl -sSL https://pdm-project.org/install-pdm.py.sha256 | shasum -a 256 -c -
      python3 install-pdm.py
      pdm sync
      sudo apt update
      sudo apt install clang-19
      sudo apt install gnuplot
    shell: bash

  - name: Lint
    run: |
      PROJECT_SRC_REL="src/stdbench" ./lint.sh
    shell: bash

  - name: PDM install
    run: pdm install
    shell: bash

  - name: conan install
    run: |
      source .venv/bin/activate
      conan --version
      conan profile detect
      conan install . -s compiler.cppstd=17 -s compiler.version=11
    shell: bash

  - name: test
    run: |
      source .venv/bin/activate
      conan install . -s compiler.cppstd=17 -s compiler.version=11
      pdm run pytest -s -o log_level=DEBUG -o log_cli=True tests/test_benchmarks.py
      ./build.sh
      ./test.sh
    shell: bash

